---
- name: i want to change template
  template:
         src: template/vertex.j2
         dest: /var/www/html/index.html
  notify: restarted
  
  handlers:
      - name: restart
        service:
           name: apache2
           state: restarted

