---
- name: i want to install webserver
  apt:
      name: apache2
      state: present
  notify: restartwebserver
- name: i want to change template
  template:
         src: vertex.j2
         dest: /var/www, public_html
  notify: restartwebserver
 
  handlers:
      - name: restartwebserver
        service:
           name: apache2
           state: restarted